### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by MuruganChandrasekar** [mcci-catena/docker-iot-dashboard#71]
Please release the HEAD.

HEAD includes the following changes

- Included auxiliary backup container(cron-backup) for providing backup support for Nginx, Node-red and Grafana containers.

- Updated the base images used in all Dockerfile from bionic to focal.
- Added Mosquitto(MQTT client) Ubuntu ppa repository to install the latest version and fixed ownership issue when accessing Let's encrypt certs.
- Added TLS/SSL based SMTP authentication support in Postfix container.
- Some minor changes in the following files: Dockerfile, docker-compose.yml, setup.md and shell scripts.

**Comment by terrillmoore** [comment]
Closed  by #72
